name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Build a GWSL Release'
        default: 'World'
        required: true
      version:
        description: "Version"
        default: "145_MSIX_build_3"
        required: true

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygame
          pip install pywin32
          pip install winshell
          pip install Pillow
          pip install imtools
          pip install infi.systray
          pip install keyboard
          pip install pyinstaller

      - name: Building 
        run: |
          python build.py ${{ github.event.inputs.version }}

      - name: Zip build artifacts
        run: |
          powershell Compress-Archive -Path "dist/GWSL_${{ github.event.inputs.version }}" -DestinationPath "dist/GWSL_${{ github.event.inputs.version }}.zip"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gwsl-build
          path: dist/GWSL_${{ github.event.inputs.version }}.zip
